# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DirNegCurvRcpp <- function(which_par, gr, hess) {
    .Call(`_BoostingLVM_DirNegCurvRcpp`, which_par, gr, hess)
}

DirNetwRcpp <- function(gr, hess, escl) {
    .Call(`_BoostingLVM_DirNetwRcpp`, gr, hess, escl)
}

bi_prob_Rcpp <- function(tau_i, tau_j, vary_ij) {
    .Call(`_BoostingLVM_bi_prob_Rcpp`, tau_i, tau_j, vary_ij)
}

lik_fa2Rcpp <- function(par, bifreq, nitems, D) {
    .Call(`_BoostingLVM_lik_fa2Rcpp`, par, bifreq, nitems, D)
}

grad_lik_fa2Rcpp <- function(par, bifreq, nitems, D) {
    .Call(`_BoostingLVM_grad_lik_fa2Rcpp`, par, bifreq, nitems, D)
}

der_lik_fa2Rcpp <- function(par, bifreq, nitems, D) {
    .Call(`_BoostingLVM_der_lik_fa2Rcpp`, par, bifreq, nitems, D)
}

